include ~/.config/omarchy/current/theme/kitty.conf

# --- Font ---
font_family MonaspiceAr Nerd Font
font_size        11.0
bold_font        MonaspiceAr Nerd Font Bold
italic_font      MonaspiceAr Nerd Font Italic
bold_italic_font MonaspiceAr Nerd Font BoldItalic

# --- For the font clipping
modify_font cell_width 112%


# Window
window_padding_width 4
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0

# Keybindings
map F11 toggle_fullscreen
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell yes

# --- NEW: Matching Ghostty Background ---
background_opacity 0.55
#background_tint 0.9
background_image_layout scaled
background_image /home/varun/Pictures/terminal_wallpapers/5.0.png
background_blur 20

# --- NEW: Smooth Cursor Trail ---
# 1 is minimum, 3 is standard. Higher = longer trail.
cursor            #94e8e3
cursor_trail 3
# Controls how fast the trail fades (min_decay, max_decay)
cursor_trail_decay 0.1 0.4

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

