# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 3
    gaps_out = 6
    border_size = 2

    # Use master layout instead of dwindle
    # layout = master
}

# animations {
#     enabled = true
#     bezier = overshot, 0.05, 0.9, 0.1, 1.1
#
#     # animation = NAME, ON/OFF, SPEED, CURVE, STYLE
#     # Reduced speed from 7 -> 4 for windows
#     animation = windows, 1, 4, overshot, slide      
#     animation = windowsIn, 1, 4, overshot, popin 80% 
#     animation = windowsOut, 1, 4, default, popin 80%
#
#     # Borders and Fades feel better when they are very fast
#     animation = border, 1, 5, default
#     animation = fade, 1, 4, default
#
#     # Workspaces: 6 -> 3.5 makes switching feel instantaneous but smooth
#     animation = workspaces, 1, 3.5, default, slide     
# }

# HyDE custom animations
animations {
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 15
    # # Add a drop shadow for depth
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
    blur {
        enabled = true
        size = 3
        passes = 1
        new_optimizations = true
    }
    # Dim inactive windows to focus on the new one
    # dim_inactive = true
    # dim_strength = 0.15
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
