# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
# env = GDK_SCALE,2
# monitor=,preferred,auto,auto

# Good compromise for 27" or 32" 4K monitors (but fractional!)
env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.666667

# Straight 1x setup for low-resolution displays like 1080p or 1440p
# env = GDK_SCALE,1
# 1. Left Monitor (HP V243 - DP-6)
# Positioned to the left of the center monitor (-1920 offset)
# monitor=DP-6,1920x1080@60,-1920x0,1
# monitor=DP-6,1280x1024@60,-1280x0,1

# 1. Center/Main Monitor (HP P22v G5 - HDMI)
# This acts as the anchor point (0x0)
monitor=HDMI-A-1,1920x1080@60,0x0,1

# 2. Left Monitor (HP E242 - Vertical)
# - Position: To be on the left, the X-coordinate must be negative.
# - Since it is rotated (1080 wide), we use -1080.
# - Y-offset: To center it vertically against the 1080p main screen, 
#   we use (1920 - 1080) / 2 = 420. So we shift it up by -420.
monitor=DP-6, 1920x1080@60, -1080x-640, 1, transform, 1

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = eDP-1, 2880x1920@120, auto, 2
